name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@hcmkt.dev:22/skydiving-frontend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
